export const ROOT_HELP = `sander - AI-agent sandbox manager

Usage:
  sander <command> [options] [arguments]

Commands:
  create   Create a new sandbox
  setup    Generate the .sander/ bootstrap scripts for the current project
  config   Read or write sander configuration
  run      Run a prompt inside a sandbox (headless)
  attach   Attach an interactive session to a sandbox
  exec     Run a single command inside a sandbox
  stop     Stop a sandbox
  start    Start a sandbox
  rm, destroy, delete, remove   Remove a sandbox
  list     List all registered sandboxes
  logs     Show a sandbox's logs
  sync     Sync the worktree between the box and the host (one-shot, --watch, --stop)

Options:
  -h, --help  Show this help

Run "sander help <command>" for command-specific help.
`;

export function helpForCommand(command: string): string {
  switch (command) {
    case 'create':
      return `Usage: sander create [<id> | --name <id>] [--harness <name>] [--provider <name>] [--token <token>] [--yolo] [--no-yolo] [--no-watch] [--skip-install] [--skip-start] [--skip-setup] [--attach] [--quick-agent] [-p <text> | --prompt <text>] [--agent <name>] [--debug]\n\nCreate a new sandbox for the current project: teleport the project into an\nisolated box (respecting .gitignore, keeping heavy dependencies), sync the\nchosen harness's global config inside the box, and register it.\nThe sandbox id can be passed positionally (sander create <id>) or with\n--name <id>; both forms are equivalent.\nNames must be valid git branch names (up to 180 chars; no spaces or\n~ ^ : ? * [ \\, no .., @{, a lone @, leading -, leading/trailing /, //,\ntrailing ., or components starting with . or ending with .lock). The git\nbranch is created with the exact name you give. Characters docker forbids\n(such as /, @, {, } and Unicode) are mapped deterministically to a docker-safe\ncontainer name used internally by the box engine; you keep typing the original id.\nThe GitHub token is optional: resolved by precedence --token, global config,\nworkspace config. If none is specified, no token is injected and create proceeds\nwith a notice. When a token is used it is injected into the box as\nGITHUB_TOKEN/GH_TOKEN without ever touching disk; a project .env.sander file is\ncopied into the box as .env for file-based setups.\nYolo mode: the box runs yolo by default (opencode ask rules become allow,\nclaude defaultMode bypassPermissions, codex approval_policy never). Pass\n--no-yolo to require approval (opencode gains the "*": "ask" catch-all, claude\ndefaultMode default, codex approval_policy on-request) or --yolo to force yolo\neven when the config says otherwise. The mode follows flag > workspace config >\nglobal config > true and is applied to the harness config inside the box at\ncreate time and recorded per box in the registry (a box without the field is\nyolo). Limitation: the injection happens only at create; starting the engine\ndirectly (e.g. "agentbox … start") re-syncs host config over the box volume\nand can remove the yolo injection — "sander start" never re-syncs.\nBootstrap: if the project has .sander/install.sh and/or .sander/start.sh\n(generated by "sander setup"), create runs install.sh once inside the box and\nlaunches the service supervisor for start.sh. Pass --skip-install,\n--skip-start, or --skip-setup (-s) to skip either or both.\nSync: por defecto create levanta el watcher de sync en background del host\n(node <bin> sync <id> --watch, detached) tras desplegar el supervisor: espeja\nel árbol de trabajo entre el box y el worktree del host cada 2 s sin tocar la\nhistoria git, para que los cambios sin commitear fluyan en ambas direcciones.\nPasa --no-watch para desactivarlo (el paso "Activando watcher de git" del\nchecklist se salta y la sync queda desactivada); si el proyecto no es un\nrepositorio git (sin worktree host) también se salta. Limitación v1: los\nborrados de archivos untracked no se propagan.\nQuick-start: --attach (-x) opens an interactive session on the new sandbox as\nsoon as create finishes (same as "sander attach <id>"); the session's exit code\nbecomes sander's exit code. --quick-agent (-y) does the same and also launches\nthe sandbox's harness (opencode when opencode was selected) inside the session.\nThe shorts bundle: -xy means both, and then only the agent quick-start runs.\n-p <text> / --prompt <text>: create, launch the harness headless with the prompt\ninside the box (like "sander run <id> <text>", streamed live) and exit when\nthe agent finishes (implies the -y quick-start).\n--agent <name>: pass --agent <name> to the harness launch; supported by opencode\nand claude, warned and ignored by others; requires -y/--quick-agent or\n-p/--prompt.\nDebug: pass --debug (or set SANDER_DEBUG=1) to print per-step and per-command\ntiming to stderr; secrets are never logged.\nDefaults: harness opencode, provider docker, yolo on.`;
    case 'setup':
      return `Usage: sander setup [--force]
       sander setup test [--time <s>]

Generate the project's bootstrap scripts (.sander/install.sh and
.sander/start.sh) for the current repository, running the configured harness
headless as the setup agent. install.sh provisions a new sandbox once on
"sander create"; start.sh is the long-running service that the supervisor
launches. If either script already exists, setup errors — use --force to
delete both and regenerate them (other .sander/ files are never touched).

The test subcommand copies the tracked project into an ephemeral
--privileged agentbox/box:dev container with its own docker daemon (a real
box runs dockerd, so install.sh sees docker like a sandbox), runs install.sh
live, keeps start.sh running for --time seconds and verifies it is still
alive, prints the captured start.sh log, and always destroys the container
and the copy — on success and failure alike. It registers no sandbox.

Options:
  --force      Delete .sander/install.sh and .sander/start.sh and regenerate them
  --time <s>   Seconds to keep start.sh running under setup test (default 5)
  -h, --help   Show this help`;
    case 'config':
      return `Usage: sander config [--provider <name>] [--harness <name>] [--token <token>] [--yolo <true|false>] [--global | --workspace]
       sander config <command> [<key>] [<value>] [--global | --workspace]

Manage sander configuration stored as JSON in the global config file
(~/.config/sander/config.json, or $SANDER_CONFIG_DIR) or the workspace
config file (<project>/.sander/config.json).

With no subcommand, the --provider/--harness/--token/--yolo flags are written to the
global config. sander then always asks interactively for the configurable keys
(provider, harness, and the optional token) that were not already passed as flags
— even when they are already configured — showing the current value as the default
(Enter keeps it). Keys provided via --provider/--harness/--token are never re-asked,
so "sander config --provider docker --harness codex --token <t>" runs with zero prompts.
The token prompt always starts blank and hides what you type (no echo): pressing
Enter leaves the current token (if any) untouched; typing a value sets or replaces
it. To remove a token use "sander config unset token". Bulk output redacts the
token (config list, config get with no key, and the final print of bare
"sander config" show "token = ***"); only an explicit "sander config get token"
prints the real value.
In a non-terminal environment bare "sander config" fails with an actionable
error instead: run "sander config list" to view the current config or
"sander config set <key> <value>" to change it.

Commands:
  set <key> <value>    Set a value (provider, harness, token, yolo, or env.<KEY>)
  get [<key>]          Print a value, or the whole config (the token is redacted in whole-config output)
  unset <key>          Remove a key (provider, harness, token, yolo, or env.<KEY>)
  list                 Print all configured keys

Options:
  --provider <name>  Write the provider to the global config
  --harness <name>   Write the harness to the global config
  --token <token>    Write the token to the global config (the wizard asks for it only when the flag is not passed; a whitespace-only value is ignored, like leaving the prompt blank)
  --yolo <true|false>  Write the yolo default to the global config (never asked for)
  --global           Operate on the global config (default)
  --workspace        Operate on the workspace config
  -h, --help         Show this help

Values are validated: provider accepts docker, daytona, hetzner, vercel and e2b; harness must be a
valid name (letters, digits and dashes); yolo must be true or false and is stored as a boolean.
Environment variables are nested under env.<KEY>. The config file always stays valid JSON.`;
    case 'run':
      return `Usage: sander run [<id> | --sandbox <id>] <prompt>\n\nRun a prompt inside a sandbox without entering it. Resolves the sandbox from\nthe registry, loads its harness (opencode or claude), and runs the prompt\nheadless with the box's injected token and environment (secrets pass through\nin memory, never to disk). Prints the harness's output and exits with its\nexit code.`;
    case 'attach':
      return `Usage: sander attach [<id> | --sandbox <id>]\n\nAttach an interactive session to a sandbox. Opens a real pass-through terminal\ninside the box (sander draws no TUI of its own), so inner TUIs such as opencode\nor claude code draw and respond normally. Launch and follow the agent by hand\nfrom the box shell. The session's exit code becomes sander's exit code.`;
    case 'exec':
      return `Usage: sander exec [<id> | --sandbox <id>] <command...>\n\nRun a single command inside a sandbox.`;
    case 'stop':
      return `Usage: sander stop [<id> | --sandbox <id>]\n\nStop a running sandbox. Also stops the sandbox service under sander's supervisor\n(.sander/start.sh) via the supervisor pidfile.`;
    case 'start':
      return `Usage: sander start [<id> | --sandbox <id>]\n\nStart a stopped sandbox. Also starts the sandbox service under sander's supervisor\n(.sander/start.sh), which restarts it whenever worktree files change; install.sh\nis never re-run. A box without start.sh starts without a service (warning).`;
    case 'destroy':
    case 'delete':
    case 'remove':
    case 'rm':
      return `Uso: sander rm [<id> | --sandbox <id>] [--dont-delete-branch]\n\nElimina un sandbox (aliases: destroy, delete, remove). Además elimina el worktree\ny la rama git que create montó para el sandbox: borrar ramas desde el host es muy\ncomplicado, así que sander borra la rama por defecto. Usa --dont-delete-branch (o\nsu sinónimo --no-delete-branch) para conservar la rama.`;
    case 'list':
      return `Uso: sander list\n\nLista los sandboxes registrados, incluidos los puertos que expone cada uno.`;
    case 'logs':
      return `Usage: sander logs [<id> | --sandbox <id>]\n\nShow a sandbox's service log (.sander/start.log) without entering it.`;
    case 'sync':
      return `Uso: sander sync [<id> | --sandbox <id>] [--watch] [--stop]

Sincroniza el árbol de trabajo entre el box (/workspace) y el worktree del
host en ambas direcciones, sin tocar la historia git. Detecta los cambios con
git status --porcelain -uall en cada lado, planifica con planSync y ejecuta
las transferencias (agentbox cp con --yes, host→box y box→host), los borrados
(fs.rmSync en el host, rm en el box) y los conflictos. Imprime un resumen:
copiados box→host, copiados host→box y conflictos.

--watch  Levanta el watcher de sync en foreground: escribe su pid en
         <configDir>/sync/<id>.pid y anota cada ciclo en
         <configDir>/sync/<id>.log (ambos fuera del árbol de trabajo, para no
         sincronizarse consigo mismo). La primera sincronización es inmediata y
         luego cada 2 s en ambas direcciones. Si el box está caído, el ciclo se
         omite y se registra en el log sin abortar el bucle (el sandbox puede
         re-crearse o reiniciarse). Los conflictos de cada ciclo quedan
         reportados en el log.
--stop   Detiene el watcher de sync del sandbox por su pidfile y limpia su
         pid/log. Con el watcher no corriendo avisa sin fallar.

Conflictos (no-interactivo): la versión del host se guarda como backup en
.sander/<rel>.sander-host y se aplica la del box.

Si el proyecto no es git (sin worktree host registrado), la sync desactivada:
no se transfiere nada. Si el box está caído o una ejecución falla, el ciclo se
omite con aviso sin abortar.

Limitaciones v1: los borrados de archivos untracked no se detectan; la
resolución de conflictos es automática (backup + sobrescribir).`;
    default:
      return ROOT_HELP;
  }
}
